### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by ghost** [Rocka84/powerprompt#1]
I get a line break at the prompt, how could I fix it ???

<img width="993" alt="image" src="https://user-images.githubusercontent.com/26000087/112195733-94445580-8c0a-11eb-8345-18104e1ae95a.png">

**Comment by Rocka84** [comment]
This is intentional by default.  
You can override `createSegmentPrompt` and remove the `\n`

See the customization example at https://github.com/Rocka84/powerprompt/blob/master/sample.powerprompt.sh#L27
